name: fitness_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  path_provider: any
  provider: any
  intl: any
  table_calendar: any
  google_fonts: any
  shared_preferences: any
  week_of_year: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_community_generator: ^3.3.0
  build_runner: any
flutter:
  uses-material-design: true
